# ClinicalNotes dataset generation (v0)

Generated for Hugging Face: https://huggingface.co/datasets/jmaasch/compositional_causal_reasoning/

Version 0.

Code by Jacqueline Maasch | April 2025

In [1]:
# General importations.
import pandas as pd
import numpy as np
import sys

sys.path.append('../compositional_causal_reasoning')

from utils import Utils
from clinical_notes import ClinicalNotes
from dataset_generator import DataSetGenerator

In [2]:
u = Utils()
dg = DataSetGenerator()

## Step 1: Get raw dataset.

In [3]:
# x levels of graphical complexity (captured by BCC size).
# y tasks per graphical complexity level.
# z samples per task.
# w replicates per sample.
# = x*y*z*w subtasks.
graph_sizes = [[6,4,6],[7,5,7]]
n_tasks_per_size = 1
n_samples_per_task = 4000
reps_per_sample = 5
bcc_type = "wheel"
n_extra_vars = 4

df = dg.get_dataset(task_generator = ClinicalNotes,
                    graph_sizes = graph_sizes,
                    n_tasks_per_size = n_tasks_per_size,
                    n_samples_per_task = n_samples_per_task, 
                    reps_per_sample = reps_per_sample, 
                    n_extra_vars = n_extra_vars, 
                    bcc_type = bcc_type)

print(df.info())
display(df.head(5))
display(df.tail(5))

<class 'pandas.DataFrame'>
RangeIndex: 40000 entries, 0 to 39999
Data columns (total 19 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Task ID                                 40000 non-null  str
 1   Context ID                              40000 non-null  object
 2   Sample ID                               40000 non-null  object
 3   Nodes per BCC                           40000 non-null  object
 4   Replicate ID                            40000 non-null  int64
 5   DAG adjacency matrix                    40000 non-null  object
 6   DAG nodes                               40000 non-null  object
 7   CCT adjacency matrix                    40000 non-null  object
 8   CCT nodes                               40000 non-null  object
 9   Exogenous variables                     40000 non-null  object
 10  Bernoulli parameters                    40000 non-null  object
 11  Global quantity                         40000 non-null  object
 12  Local quantities                        40000 non-null  object
 13  Compositions                            40000 non-null  object
 14  Causal context                          40000 non-null  str
 15  Sample context                          40000 non-null  str
 16  Factual queries                         40000 non-null  object
 17  Interventional queries (cause = True)   40000 non-null  object
 18  Interventional queries (cause = False)  40000 non-null  object
dtypes: int64(1), object(15), str(3)
memory usage: 5.8+ MB
None

,Task ID,Context ID,Sample ID,Nodes per BCC,Replicate ID,DAG adjacency matrix,DAG nodes,CCT adjacency matrix,CCT nodes,Exogenous variables,Bernoulli parameters,Global quantity,Local quantities,Compositions,Causal context,Sample context,Factual queries,Interventional queries (cause = True),Interventional queries (cause = False)
0,0.0.0,0,0,"[6, 4, 6]",0,"[[0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0], [...","[pain, Q0GK, YYQ3, ZZ30, YB2I, R13I, 80O7, WZ1...","[[0, 1, 1, 1], [0, 0, 1, 1], [0, 0, 0, 1], [0,...","[pain, R13I, WBCN, surgery]","[GKR9, 88YD, LQPZ, DQNP, HRQP, YCF2, UIUD, 4K6...","[0.8, 0.6, 0.6, 0.5, 0.6, 0.8, 0.7, 0.7, 0.6, ...","(pain, surgery)","[(pain, R13I), (pain, WBCN), (R13I, WBCN), (R1...","[[(pain, R13I), (R13I, WBCN), (WBCN, surgery)]...",Chronic disease Z0X4ZC sometimes requires surg...,"Now, we will review the history and physical n...",{'surgery': {'Prompt': 'Given these history an...,"{('pain', 'surgery'): {'Prompt': 'Now suppose ...","{('pain', 'surgery'): {'Prompt': 'Now suppose ..."
1,0.0.1,0,0,"[6, 4, 6]",1,"[[0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0], [...","[pain, Q0GK, YYQ3, ZZ30, YB2I, R13I, 80O7, WZ1...","[[0, 1, 1, 1], [0, 0, 1, 1], [0, 0, 0, 1], [0,...","[pain, R13I, WBCN, surgery]","[GKR9, 88YD, LQPZ, DQNP, HRQP, YCF2, UIUD, 4K6...","[0.8, 0.6, 0.6, 0.5, 0.6, 0.8, 0.7, 0.7, 0.6, ...","(pain, surgery)","[(pain, R13I), (pain, WBCN), (R13I, WBCN), (R1...","[[(pain, R13I), (R13I, WBCN), (WBCN, surgery)]...",Chronic disease Z0X4ZC sometimes requires surg...,"Now, we will review the history and physical n...",{'surgery': {'Prompt': 'Given these history an...,"{('pain', 'surgery'): {'Prompt': 'Now suppose ...","{('pain', 'surgery'): {'Prompt': 'Now suppose ..."
2,0.0.2,0,0,"[6, 4, 6]",2,"[[0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0], [...","[pain, Q0GK, YYQ3, ZZ30, YB2I, R13I, 80O7, WZ1...","[[0, 1, 1, 1], [0, 0, 1, 1], [0, 0, 0, 1], [0,...","[pain, R13I, WBCN, surgery]","[GKR9, 88YD, LQPZ, DQNP, HRQP, YCF2, UIUD, 4K6...","[0.8, 0.6, 0.6, 0.5, 0.6, 0.8, 0.7, 0.7, 0.6, ...","(pain, surgery)","[(pain, R13I), (pain, WBCN), (R13I, WBCN), (R1...","[[(pain, R13I), (R13I, WBCN), (WBCN, surgery)]...",Chronic disease Z0X4ZC sometimes requires surg...,"Now, we will review the history and physical n...",{'surgery': {'Prompt': 'Given these history an...,"{('pain', 'surgery'): {'Prompt': 'Now suppose ...","{('pain', 'surgery'): {'Prompt': 'Now suppose ..."
3,0.0.3,0,0,"[6, 4, 6]",3,"[[0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0], [...","[pain, Q0GK, YYQ3, ZZ30, YB2I, R13I, 80O7, WZ1...","[[0, 1, 1, 1], [0, 0, 1, 1], [0, 0, 0, 1], [0,...","[pain, R13I, WBCN, surgery]","[GKR9, 88YD, LQPZ, DQNP, HRQP, YCF2, UIUD, 4K6...","[0.8, 0.6, 0.6, 0.5, 0.6, 0.8, 0.7, 0.7, 0.6, ...","(pain, surgery)","[(pain, R13I), (pain, WBCN), (R13I, WBCN), (R1...","[[(pain, R13I), (R13I, WBCN), (WBCN, surgery)]...",Chronic disease Z0X4ZC sometimes requires surg...,"Now, we will review the history and physical n...",{'surgery': {'Prompt': 'Given these history an...,"{('pain', 'surgery'): {'Prompt': 'Now suppose ...","{('pain', 'surgery'): {'Prompt': 'Now suppose ..."
4,0.0.4,0,0,"[6, 4, 6]",4,"[[0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0], [...","[pain, Q0GK, YYQ3, ZZ30, YB2I, R13I, 80O7, WZ1...","[[0, 1, 1, 1], [0, 0, 1, 1], [0, 0, 0, 1], [0,...","[pain, R13I, WBCN, surgery]","[GKR9, 88YD, LQPZ, DQNP, HRQP, YCF2, UIUD, 4K6...","[0.8, 0.6, 0.6, 0.5, 0.6, 0.8, 0.7, 0.7, 0.6, ...","(pain, surgery)","[(pain, R13I), (pain, WBCN), (R13I, WBCN), (R1...","[[(pain, R13I), (R13I, WBCN), (WBCN, surgery)]...",Chronic disease Z0X4ZC sometimes requires surg...,"Now, we will review the history and physical n...",{'surgery': {'Prompt': 'Given these history an...,"{('pain', 'surgery'): {'Prompt': 'Now suppose ...","{('pain', 'surgery'): {'Prompt': 'Now suppose ..."

,Task ID,Context ID,Sample ID,Nodes per BCC,Replicate ID,DAG adjacency matrix,DAG nodes,CCT adjacency matrix,CCT nodes,Exogenous variables,Bernoulli parameters,Global quantity,Local quantities,Compositions,Causal context,Sample context,Factual queries,Interventional queries (cause = True),Interventional queries (cause = False)
39995,1.3999.0,1,3999,"[7, 5, 7]",0,"[[0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,...","[pain, ENPX, 7J6N, 5SSH, 0KPE, 1H79, 5EUT, FIM...","[[0, 1, 1, 1], [0, 0, 1, 1], [0, 0, 0, 1], [0,...","[pain, 5EUT, 0L8E, surgery]","[B7OY, ZXR2, 3TH3, Q5HA, FBHM, HBPJ, DVWC, 4T9...","[0.8, 0.7, 0.8, 0.8, 0.5, 0.4, 0.8, 0.6, 0.7, ...","(pain, surgery)","[(pain, 5EUT), (pain, 0L8E), (5EUT, 0L8E), (5E...","[[(pain, 5EUT), (5EUT, 0L8E), (0L8E, surgery)]...",Chronic disease U73A8B sometimes requires surg...,"Now, we will review the history and physical n...",{'surgery': {'Prompt': 'Given these history an...,"{('pain', 'surgery'): {'Prompt': 'Now suppose ...","{('pain', 'surgery'): {'Prompt': 'Now suppose ..."
39996,1.3999.1,1,3999,"[7, 5, 7]",1,"[[0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,...","[pain, ENPX, 7J6N, 5SSH, 0KPE, 1H79, 5EUT, FIM...","[[0, 1, 1, 1], [0, 0, 1, 1], [0, 0, 0, 1], [0,...","[pain, 5EUT, 0L8E, surgery]","[B7OY, ZXR2, 3TH3, Q5HA, FBHM, HBPJ, DVWC, 4T9...","[0.8, 0.7, 0.8, 0.8, 0.5, 0.4, 0.8, 0.6, 0.7, ...","(pain, surgery)","[(pain, 5EUT), (pain, 0L8E), (5EUT, 0L8E), (5E...","[[(pain, 5EUT), (5EUT, 0L8E), (0L8E, surgery)]...",Chronic disease U73A8B sometimes requires surg...,"Now, we will review the history and physical n...",{'surgery': {'Prompt': 'Given these history an...,"{('pain', 'surgery'): {'Prompt': 'Now suppose ...","{('pain', 'surgery'): {'Prompt': 'Now suppose ..."
39997,1.3999.2,1,3999,"[7, 5, 7]",2,"[[0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,...","[pain, ENPX, 7J6N, 5SSH, 0KPE, 1H79, 5EUT, FIM...","[[0, 1, 1, 1], [0, 0, 1, 1], [0, 0, 0, 1], [0,...","[pain, 5EUT, 0L8E, surgery]","[B7OY, ZXR2, 3TH3, Q5HA, FBHM, HBPJ, DVWC, 4T9...","[0.8, 0.7, 0.8, 0.8, 0.5, 0.4, 0.8, 0.6, 0.7, ...","(pain, surgery)","[(pain, 5EUT), (pain, 0L8E), (5EUT, 0L8E), (5E...","[[(pain, 5EUT), (5EUT, 0L8E), (0L8E, surgery)]...",Chronic disease U73A8B sometimes requires surg...,"Now, we will review the history and physical n...",{'surgery': {'Prompt': 'Given these history an...,"{('pain', 'surgery'): {'Prompt': 'Now suppose ...","{('pain', 'surgery'): {'Prompt': 'Now suppose ..."
39998,1.3999.3,1,3999,"[7, 5, 7]",3,"[[0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,...","[pain, ENPX, 7J6N, 5SSH, 0KPE, 1H79, 5EUT, FIM...","[[0, 1, 1, 1], [0, 0, 1, 1], [0, 0, 0, 1], [0,...","[pain, 5EUT, 0L8E, surgery]","[B7OY, ZXR2, 3TH3, Q5HA, FBHM, HBPJ, DVWC, 4T9...","[0.8, 0.7, 0.8, 0.8, 0.5, 0.4, 0.8, 0.6, 0.7, ...","(pain, surgery)","[(pain, 5EUT), (pain, 0L8E), (5EUT, 0L8E), (5E...","[[(pain, 5EUT), (5EUT, 0L8E), (0L8E, surgery)]...",Chronic disease U73A8B sometimes requires surg...,"Now, we will review the history and physical n...",{'surgery': {'Prompt': 'Given these history an...,"{('pain', 'surgery'): {'Prompt': 'Now suppose ...","{('pain', 'surgery'): {'Prompt': 'Now suppose ..."
39999,1.3999.4,1,3999,"[7, 5, 7]",4,"[[0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,...","[pain, ENPX, 7J6N, 5SSH, 0KPE, 1H79, 5EUT, FIM...","[[0, 1, 1, 1], [0, 0, 1, 1], [0, 0, 0, 1], [0,...","[pain, 5EUT, 0L8E, surgery]","[B7OY, ZXR2, 3TH3, Q5HA, FBHM, HBPJ, DVWC, 4T9...","[0.8, 0.7, 0.8, 0.8, 0.5, 0.4, 0.8, 0.6, 0.7, ...","(pain, surgery)","[(pain, 5EUT), (pain, 0L8E), (5EUT, 0L8E), (5E...","[[(pain, 5EUT), (5EUT, 0L8E), (0L8E, surgery)]...",Chronic disease U73A8B sometimes requires surg...,"Now, we will review the history and physical n...",{'surgery': {'Prompt': 'Given these history an...,"{('pain', 'surgery'): {'Prompt': 'Now suppose ...","{('pain', 'surgery'): {'Prompt': 'Now suppose ..."

## Step 2: Process factual and counterfactual prompts.

In [4]:
# Process prompts.
df_factual, df_cf = dg.process_prompts()

In [5]:
print(df_factual.info())
display(df_factual.head(5))

<class 'pandas.DataFrame'>
RangeIndex: 120000 entries, 0 to 119999
Data columns (total 9 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   Task ID        120000 non-null  str
 1   Context ID     120000 non-null  int64
 2   Sample ID      120000 non-null  int64
 3   Replicate ID   120000 non-null  int64
 4   Nodes per BCC  120000 non-null  object
 5   Effect         120000 non-null  str
 6   Context        120000 non-null  str
 7   Question       120000 non-null  str
 8   True           120000 non-null  int64
dtypes: int64(4), object(1), str(4)
memory usage: 8.2+ MB
None

,Task ID,Context ID,Sample ID,Replicate ID,Nodes per BCC,Effect,Context,Question,True
0,0.0.0,0,0,0,"[6, 4, 6]",surgery,Chronic disease Z0X4ZC sometimes requires surg...,"Given these history and physical notes, will t...",1
1,0.0.0,0,0,0,"[6, 4, 6]",R13I,Chronic disease Z0X4ZC sometimes requires surg...,"Given these history and physical notes, will l...",1
2,0.0.0,0,0,0,"[6, 4, 6]",WBCN,Chronic disease Z0X4ZC sometimes requires surg...,"Given these history and physical notes, will l...",1
3,0.0.1,0,0,1,"[6, 4, 6]",surgery,Chronic disease Z0X4ZC sometimes requires surg...,"Given these history and physical notes, will t...",1
4,0.0.1,0,0,1,"[6, 4, 6]",R13I,Chronic disease Z0X4ZC sometimes requires surg...,"Given these history and physical notes, will l...",1

In [6]:
print(df_cf.info())
display(df_cf.head(5))

<class 'pandas.DataFrame'>
RangeIndex: 240000 entries, 0 to 239999
Data columns (total 13 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   Task ID                   240000 non-null  str
 1   Context ID                240000 non-null  int64
 2   Sample ID                 240000 non-null  int64
 3   Replicate ID              240000 non-null  int64
 4   Nodes per BCC             240000 non-null  object
 5   Cause-effect pair         240000 non-null  object
 6   Cause                     240000 non-null  str
 7   Effect                    240000 non-null  str
 8   Context                   240000 non-null  str
 9   Question (cause = True)   240000 non-null  str
 10  True (cause = True)       240000 non-null  int64
 11  Question (cause = False)  240000 non-null  str
 12  True (cause = False)      240000 non-null  int64
dtypes: int64(5), object(2), str(6)
memory usage: 23.8+ MB
None

,Task ID,Context ID,Sample ID,Replicate ID,Nodes per BCC,Cause-effect pair,Cause,Effect,Context,Question (cause = True),True (cause = True),Question (cause = False),True (cause = False)
0,0.0.0,0,0,0,"[6, 4, 6]","(pain, surgery)",pain,surgery,Chronic disease Z0X4ZC sometimes requires surg...,Now suppose that the patient will be in signif...,1,Now suppose that the patient will not be in pa...,1
1,0.0.0,0,0,0,"[6, 4, 6]","(pain, R13I)",pain,R13I,Chronic disease Z0X4ZC sometimes requires surg...,Now suppose that the patient will be in signif...,1,Now suppose that the patient will not be in pa...,1
2,0.0.0,0,0,0,"[6, 4, 6]","(pain, WBCN)",pain,WBCN,Chronic disease Z0X4ZC sometimes requires surg...,Now suppose that the patient will be in signif...,1,Now suppose that the patient will not be in pa...,1
3,0.0.0,0,0,0,"[6, 4, 6]","(R13I, WBCN)",R13I,WBCN,Chronic disease Z0X4ZC sometimes requires surg...,Now suppose that lab R13I will be low regardle...,1,Now suppose that lab R13I will not be low rega...,1
4,0.0.0,0,0,0,"[6, 4, 6]","(R13I, surgery)",R13I,surgery,Chronic disease Z0X4ZC sometimes requires surg...,Now suppose that lab R13I will be low regardle...,1,Now suppose that lab R13I will not be low rega...,1

In [7]:
l = len(df_factual[(df_factual["Context ID"] == 0) & (df_factual["Effect"] == "surgery")])
print("\nTotal factual q's per quantity per task:", l)

Total factual q's per quantity per task: 20000

In [8]:
l = len(df_cf[(df_cf["Context ID"] == 0) & (df_cf["Cause-effect pair"] == ("pain", "surgery"))])
print("\nTotal counterfactual q's per quantity per task:", l)

Total counterfactual q's per quantity per task: 20000

## Step 3: Get ground truth PNS values.

Get dictionary mapping cause-effect pairs to their PNS value.

Keys are the Context ID. Values are dictionaries whose keys are the cause-effect pair and whose values are the finite sample PNS computed using ground truth response vectors.

In [9]:
pns_dict = dg.get_pns_dict(verbose = False)
display(pns_dict)

{np.int64(0): {"('pain', 'surgery')": np.float64(0.0),
  "('pain', 'R13I')": np.float64(0.00425),
  "('pain', 'WBCN')": np.float64(0.0),
  "('R13I', 'WBCN')": np.float64(0.04),
  "('R13I', 'surgery')": np.float64(0.02775),
  "('WBCN', 'surgery')": np.float64(0.70025),
  "[('pain', 'R13I'), ('R13I', 'WBCN'), ('WBCN', 'surgery')]": np.float64(0.00011904250000000001),
  "[('pain', 'R13I'), ('R13I', 'surgery')]": np.float64(0.00011793750000000001),
  "[('pain', 'WBCN'), ('WBCN', 'surgery')]": np.float64(0.0)},
 np.int64(1): {"('pain', 'surgery')": np.float64(0.0),
  "('pain', '5EUT')": np.float64(0.00125),
  "('pain', '0L8E')": np.float64(0.0),
  "('5EUT', '0L8E')": np.float64(0.024),
  "('5EUT', 'surgery')": np.float64(0.01075),
  "('0L8E', 'surgery')": np.float64(0.3935),
  "[('pain', '5EUT'), ('5EUT', '0L8E'), ('0L8E', 'surgery')]": np.float64(1.1805000000000001e-05),
  "[('pain', '5EUT'), ('5EUT', 'surgery')]": np.float64(1.34375e-05),
  "[('pain', '0L8E'), ('0L8E', 'surgery')]": np.float64(0.0)}}

## Step 4: Compute internal consistency thresholds.

Return a dictionary that maps compositions to their correctness threshold
for internal compositional consistency evaluation. Thresholds are the RAE
for each composition relative to the global quantity of interest, times a
multiplier of the user's choice. 

* RAE = (abs(global PNS - composition PNS) / global PNS)
* Threhold = RAE*multiplier
        
This method of obtaining the threshold accounts for the innate error owed
to PNS estimation on finite samples, while the multiplier represents the
user's tolerance level for errors larger than the finite sample error.

Keys are the Context ID. Values are dictionaries whose keys are the causal composition (denoted by a list of cause-effect pairs whose PNS values are multiplied) and whose values are the internal consistency threshold.

For public use, we export threholds with multiplier 1.0 so that the end user can select 
their own multiplier downstream.

In [10]:
# Not for export.
threshold_dict = dg.get_internal_consistency_thresholds(multiplier = 1.25)
display(threshold_dict)

/Users/yuchen/Desktop/notebook-benchmark/benchmarks/test/clinic_notes/../compositional_causal_reasoning/dataset_generator.py:282: RuntimeWarning: divide by zero encountered in scalar divide
  context_dict[str(comp)] = (abs(glo_pns - comp_pns) / glo_pns)*multiplier
/Users/yuchen/Desktop/notebook-benchmark/benchmarks/test/clinic_notes/../compositional_causal_reasoning/dataset_generator.py:282: RuntimeWarning: invalid value encountered in scalar divide
  context_dict[str(comp)] = (abs(glo_pns - comp_pns) / glo_pns)*multiplier

{0: {"[('pain', 'R13I'), ('R13I', 'WBCN'), ('WBCN', 'surgery')]": np.float64(inf),
  "[('pain', 'R13I'), ('R13I', 'surgery')]": np.float64(inf),
  "[('pain', 'WBCN'), ('WBCN', 'surgery')]": np.float64(nan)},
 1: {"[('pain', '5EUT'), ('5EUT', '0L8E'), ('0L8E', 'surgery')]": np.float64(inf),
  "[('pain', '5EUT'), ('5EUT', 'surgery')]": np.float64(inf),
  "[('pain', '0L8E'), ('0L8E', 'surgery')]": np.float64(nan)}}

In [11]:
# For export.
threshold_dict = dg.get_internal_consistency_thresholds(multiplier = 1.0)
display(threshold_dict)

{0: {"[('pain', 'R13I'), ('R13I', 'WBCN'), ('WBCN', 'surgery')]": np.float64(inf),
  "[('pain', 'R13I'), ('R13I', 'surgery')]": np.float64(inf),
  "[('pain', 'WBCN'), ('WBCN', 'surgery')]": np.float64(nan)},
 1: {"[('pain', '5EUT'), ('5EUT', '0L8E'), ('0L8E', 'surgery')]": np.float64(inf),
  "[('pain', '5EUT'), ('5EUT', 'surgery')]": np.float64(inf),
  "[('pain', '0L8E'), ('0L8E', 'surgery')]": np.float64(nan)}}