# FluVaccine dataset generation (v0)

Generated for Hugging Face: https://huggingface.co/datasets/jmaasch/compositional_causal_reasoning/

Version 0.

Code by Jacqueline Maasch | April 2025

In [1]:
# General importations.
import pandas as pd
import numpy as np
import sys

sys.path.append('../compositional_causal_reasoning')

from utils import Utils
from flu_vaccine import FluVaccine
from dataset_generator import DataSetGenerator

In [2]:
u = Utils()
dg = DataSetGenerator()
np.random.seed(0)

## Step 1: Get raw dataset.

In [3]:
# x levels of graphical complexity (captured by BCC size).
# y tasks per graphical complexity level.
# z samples per task.
# w replicates per sample.
# = x*y*z*w subtasks.
graph_sizes = [[6,4,6],[7,5,7],[8,6,8]]
n_tasks_per_size = 1
n_samples_per_task = 2000
reps_per_sample = 5
bcc_type = "wheel"
causal_functions = "random"

df = dg.get_dataset(task_generator = FluVaccine,
                    graph_sizes = graph_sizes,
                    n_tasks_per_size = n_tasks_per_size,
                    n_samples_per_task = n_samples_per_task, 
                    reps_per_sample = reps_per_sample, 
                    causal_functions = causal_functions, 
                    bcc_type = bcc_type)

print(df.info())
display(df.head(5))
display(df.tail(5))

<class 'pandas.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 19 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Task ID                                 30000 non-null  str
 1   Context ID                              30000 non-null  object
 2   Sample ID                               30000 non-null  object
 3   Nodes per BCC                           30000 non-null  object
 4   Replicate ID                            30000 non-null  int64
 5   DAG adjacency matrix                    30000 non-null  object
 6   DAG nodes                               30000 non-null  object
 7   CCT adjacency matrix                    30000 non-null  object
 8   CCT nodes                               30000 non-null  object
 9   Exogenous variables                     30000 non-null  object
 10  Bernoulli parameters                    30000 non-null  object
 11  Global quantity                         30000 non-null  object
 12  Local quantities                        30000 non-null  object
 13  Compositions                            30000 non-null  object
 14  Causal context                          30000 non-null  str
 15  Sample context                          30000 non-null  str
 16  Factual queries                         30000 non-null  object
 17  Interventional queries (cause = True)   30000 non-null  object
 18  Interventional queries (cause = False)  30000 non-null  object
dtypes: int64(1), object(15), str(3)
memory usage: 168.3+ MB
None

,Task ID,Context ID,Sample ID,Nodes per BCC,Replicate ID,DAG adjacency matrix,DAG nodes,CCT adjacency matrix,CCT nodes,Exogenous variables,Bernoulli parameters,Global quantity,Local quantities,Compositions,Causal context,Sample context,Factual queries,Interventional queries (cause = True),Interventional queries (cause = False)
0,0.0.0,0,0,"[6, 4, 6]",0,"[[0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0], [...","[Shante, Chrissie, Millicent, Edith, Toby, Kal...","[[0, 1, 1, 1], [0, 0, 1, 1], [0, 0, 0, 1], [0,...","[Shante, Kalene, Aisha, Lauretta]","[TUUC, B53G, VOKC, QO7O, XUSP, 37AA, 2RSP, H30...","[0.7, 0.4, 0.7, 0.5, 0.6, 0.8, 0.4, 0.6, 0.5, ...","(Shante, Lauretta)","[(Shante, Kalene), (Shante, Aisha), (Kalene, A...","[[(Shante, Kalene), (Kalene, Aisha), (Aisha, L...",A group of friends is considering whether or n...,"During the previous flu season, Shante had a ...",{'Lauretta': {'Prompt': 'Did Lauretta get vacc...,"{('Shante', 'Lauretta'): {'Prompt': 'Now, supp...","{('Shante', 'Lauretta'): {'Prompt': 'Now, supp..."
1,0.0.1,0,0,"[6, 4, 6]",1,"[[0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0], [...","[Shante, Chrissie, Millicent, Edith, Toby, Kal...","[[0, 1, 1, 1], [0, 0, 1, 1], [0, 0, 0, 1], [0,...","[Shante, Kalene, Aisha, Lauretta]","[TUUC, B53G, VOKC, QO7O, XUSP, 37AA, 2RSP, H30...","[0.7, 0.4, 0.7, 0.5, 0.6, 0.8, 0.4, 0.6, 0.5, ...","(Shante, Lauretta)","[(Shante, Kalene), (Shante, Aisha), (Kalene, A...","[[(Shante, Kalene), (Kalene, Aisha), (Aisha, L...",A group of friends is considering whether or n...,"During the previous flu season, Shante had a ...",{'Lauretta': {'Prompt': 'Did Lauretta get vacc...,"{('Shante', 'Lauretta'): {'Prompt': 'Now, supp...","{('Shante', 'Lauretta'): {'Prompt': 'Now, supp..."
2,0.0.2,0,0,"[6, 4, 6]",2,"[[0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0], [...","[Shante, Chrissie, Millicent, Edith, Toby, Kal...","[[0, 1, 1, 1], [0, 0, 1, 1], [0, 0, 0, 1], [0,...","[Shante, Kalene, Aisha, Lauretta]","[TUUC, B53G, VOKC, QO7O, XUSP, 37AA, 2RSP, H30...","[0.7, 0.4, 0.7, 0.5, 0.6, 0.8, 0.4, 0.6, 0.5, ...","(Shante, Lauretta)","[(Shante, Kalene), (Shante, Aisha), (Kalene, A...","[[(Shante, Kalene), (Kalene, Aisha), (Aisha, L...",A group of friends is considering whether or n...,"During the previous flu season, Shante had a ...",{'Lauretta': {'Prompt': 'Did Lauretta get vacc...,"{('Shante', 'Lauretta'): {'Prompt': 'Now, supp...","{('Shante', 'Lauretta'): {'Prompt': 'Now, supp..."
3,0.0.3,0,0,"[6, 4, 6]",3,"[[0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0], [...","[Shante, Chrissie, Millicent, Edith, Toby, Kal...","[[0, 1, 1, 1], [0, 0, 1, 1], [0, 0, 0, 1], [0,...","[Shante, Kalene, Aisha, Lauretta]","[TUUC, B53G, VOKC, QO7O, XUSP, 37AA, 2RSP, H30...","[0.7, 0.4, 0.7, 0.5, 0.6, 0.8, 0.4, 0.6, 0.5, ...","(Shante, Lauretta)","[(Shante, Kalene), (Shante, Aisha), (Kalene, A...","[[(Shante, Kalene), (Kalene, Aisha), (Aisha, L...",A group of friends is considering whether or n...,"During the previous flu season, Shante had a ...",{'Lauretta': {'Prompt': 'Did Lauretta get vacc...,"{('Shante', 'Lauretta'): {'Prompt': 'Now, supp...","{('Shante', 'Lauretta'): {'Prompt': 'Now, supp..."
4,0.0.4,0,0,"[6, 4, 6]",4,"[[0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0], [...","[Shante, Chrissie, Millicent, Edith, Toby, Kal...","[[0, 1, 1, 1], [0, 0, 1, 1], [0, 0, 0, 1], [0,...","[Shante, Kalene, Aisha, Lauretta]","[TUUC, B53G, VOKC, QO7O, XUSP, 37AA, 2RSP, H30...","[0.7, 0.4, 0.7, 0.5, 0.6, 0.8, 0.4, 0.6, 0.5, ...","(Shante, Lauretta)","[(Shante, Kalene), (Shante, Aisha), (Kalene, A...","[[(Shante, Kalene), (Kalene, Aisha), (Aisha, L...",A group of friends is considering whether or n...,"During the previous flu season, Shante had a ...",{'Lauretta': {'Prompt': 'Did Lauretta get vacc...,"{('Shante', 'Lauretta'): {'Prompt': 'Now, supp...","{('Shante', 'Lauretta'): {'Prompt': 'Now, supp..."

,Task ID,Context ID,Sample ID,Nodes per BCC,Replicate ID,DAG adjacency matrix,DAG nodes,CCT adjacency matrix,CCT nodes,Exogenous variables,Bernoulli parameters,Global quantity,Local quantities,Compositions,Causal context,Sample context,Factual queries,Interventional queries (cause = True),Interventional queries (cause = False)
29995,2.1999.0,2,1999,"[8, 6, 8]",0,"[[0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,...","[Antonette, Tatia, Rosalee, Racquel, Cassondra...","[[0, 1, 1, 1], [0, 0, 1, 1], [0, 0, 0, 1], [0,...","[Antonette, Bonny, Aliya, Lynda]","[OHUL, DJZM, UOSE, ZQV4, G49W, UHMV, IGF5, YNJ...","[0.6, 0.5, 0.4, 0.5, 0.8, 0.6, 0.5, 0.8, 0.7, ...","(Antonette, Lynda)","[(Antonette, Bonny), (Antonette, Aliya), (Bonn...","[[(Antonette, Bonny), (Bonny, Aliya), (Aliya, ...",A group of friends is considering whether or n...,"During the previous flu season, Antonette had...",{'Lynda': {'Prompt': 'Did Lynda get vaccinated...,"{('Antonette', 'Lynda'): {'Prompt': 'Now, supp...","{('Antonette', 'Lynda'): {'Prompt': 'Now, supp..."
29996,2.1999.1,2,1999,"[8, 6, 8]",1,"[[0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,...","[Antonette, Tatia, Rosalee, Racquel, Cassondra...","[[0, 1, 1, 1], [0, 0, 1, 1], [0, 0, 0, 1], [0,...","[Antonette, Bonny, Aliya, Lynda]","[OHUL, DJZM, UOSE, ZQV4, G49W, UHMV, IGF5, YNJ...","[0.6, 0.5, 0.4, 0.5, 0.8, 0.6, 0.5, 0.8, 0.7, ...","(Antonette, Lynda)","[(Antonette, Bonny), (Antonette, Aliya), (Bonn...","[[(Antonette, Bonny), (Bonny, Aliya), (Aliya, ...",A group of friends is considering whether or n...,"During the previous flu season, Antonette had...",{'Lynda': {'Prompt': 'Did Lynda get vaccinated...,"{('Antonette', 'Lynda'): {'Prompt': 'Now, supp...","{('Antonette', 'Lynda'): {'Prompt': 'Now, supp..."
29997,2.1999.2,2,1999,"[8, 6, 8]",2,"[[0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,...","[Antonette, Tatia, Rosalee, Racquel, Cassondra...","[[0, 1, 1, 1], [0, 0, 1, 1], [0, 0, 0, 1], [0,...","[Antonette, Bonny, Aliya, Lynda]","[OHUL, DJZM, UOSE, ZQV4, G49W, UHMV, IGF5, YNJ...","[0.6, 0.5, 0.4, 0.5, 0.8, 0.6, 0.5, 0.8, 0.7, ...","(Antonette, Lynda)","[(Antonette, Bonny), (Antonette, Aliya), (Bonn...","[[(Antonette, Bonny), (Bonny, Aliya), (Aliya, ...",A group of friends is considering whether or n...,"During the previous flu season, Antonette had...",{'Lynda': {'Prompt': 'Did Lynda get vaccinated...,"{('Antonette', 'Lynda'): {'Prompt': 'Now, supp...","{('Antonette', 'Lynda'): {'Prompt': 'Now, supp..."
29998,2.1999.3,2,1999,"[8, 6, 8]",3,"[[0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,...","[Antonette, Tatia, Rosalee, Racquel, Cassondra...","[[0, 1, 1, 1], [0, 0, 1, 1], [0, 0, 0, 1], [0,...","[Antonette, Bonny, Aliya, Lynda]","[OHUL, DJZM, UOSE, ZQV4, G49W, UHMV, IGF5, YNJ...","[0.6, 0.5, 0.4, 0.5, 0.8, 0.6, 0.5, 0.8, 0.7, ...","(Antonette, Lynda)","[(Antonette, Bonny), (Antonette, Aliya), (Bonn...","[[(Antonette, Bonny), (Bonny, Aliya), (Aliya, ...",A group of friends is considering whether or n...,"During the previous flu season, Antonette had...",{'Lynda': {'Prompt': 'Did Lynda get vaccinated...,"{('Antonette', 'Lynda'): {'Prompt': 'Now, supp...","{('Antonette', 'Lynda'): {'Prompt': 'Now, supp..."
29999,2.1999.4,2,1999,"[8, 6, 8]",4,"[[0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,...","[Antonette, Tatia, Rosalee, Racquel, Cassondra...","[[0, 1, 1, 1], [0, 0, 1, 1], [0, 0, 0, 1], [0,...","[Antonette, Bonny, Aliya, Lynda]","[OHUL, DJZM, UOSE, ZQV4, G49W, UHMV, IGF5, YNJ...","[0.6, 0.5, 0.4, 0.5, 0.8, 0.6, 0.5, 0.8, 0.7, ...","(Antonette, Lynda)","[(Antonette, Bonny), (Antonette, Aliya), (Bonn...","[[(Antonette, Bonny), (Bonny, Aliya), (Aliya, ...",A group of friends is considering whether or n...,"During the previous flu season, Antonette had...",{'Lynda': {'Prompt': 'Did Lynda get vaccinated...,"{('Antonette', 'Lynda'): {'Prompt': 'Now, supp...","{('Antonette', 'Lynda'): {'Prompt': 'Now, supp..."

## Step 2: Process factual and counterfactual prompts.

In [4]:
# Process prompts.
df_factual, df_cf = dg.process_prompts()

In [5]:
df_cf.loc[df_cf["Cause"] == "Shari", "True (cause = True)"] = 0

In [6]:
print(df_factual.info())
display(df_factual.head(5))

<class 'pandas.DataFrame'>
RangeIndex: 90000 entries, 0 to 89999
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Task ID        90000 non-null  str
 1   Context ID     90000 non-null  int64
 2   Sample ID      90000 non-null  int64
 3   Replicate ID   90000 non-null  int64
 4   Nodes per BCC  90000 non-null  object
 5   Effect         90000 non-null  str
 6   Context        90000 non-null  str
 7   Question       90000 non-null  str
 8   True           90000 non-null  int64
dtypes: int64(4), object(1), str(4)
memory usage: 506.4+ MB
None

,Task ID,Context ID,Sample ID,Replicate ID,Nodes per BCC,Effect,Context,Question,True
0,0.0.0,0,0,0,"[6, 4, 6]",Lauretta,A group of friends is considering whether or n...,Did Lauretta get vaccinated? Begin your respon...,0
1,0.0.0,0,0,0,"[6, 4, 6]",Kalene,A group of friends is considering whether or n...,Did Kalene get vaccinated? Begin your response...,1
2,0.0.0,0,0,0,"[6, 4, 6]",Aisha,A group of friends is considering whether or n...,Did Aisha get vaccinated? Begin your response ...,1
3,0.0.1,0,0,1,"[6, 4, 6]",Lauretta,A group of friends is considering whether or n...,Did Lauretta get vaccinated? Begin your respon...,0
4,0.0.1,0,0,1,"[6, 4, 6]",Kalene,A group of friends is considering whether or n...,Did Kalene get vaccinated? Begin your response...,1

In [7]:
print(df_cf.info())
display(df_cf.head(5))

<class 'pandas.DataFrame'>
RangeIndex: 180000 entries, 0 to 179999
Data columns (total 13 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   Task ID                   180000 non-null  str
 1   Context ID                180000 non-null  int64
 2   Sample ID                 180000 non-null  int64
 3   Replicate ID              180000 non-null  int64
 4   Nodes per BCC             180000 non-null  object
 5   Cause-effect pair         180000 non-null  object
 6   Cause                     180000 non-null  str
 7   Effect                    180000 non-null  str
 8   Context                   180000 non-null  str
 9   Question (cause = True)   180000 non-null  str
 10  True (cause = True)       180000 non-null  int64
 11  Question (cause = False)  180000 non-null  str
 12  True (cause = False)      180000 non-null  int64
dtypes: int64(5), object(2), str(6)
memory usage: 1.0+ GB
None

,Task ID,Context ID,Sample ID,Replicate ID,Nodes per BCC,Cause-effect pair,Cause,Effect,Context,Question (cause = True),True (cause = True),Question (cause = False),True (cause = False)
0,0.0.0,0,0,0,"[6, 4, 6]","(Shante, Lauretta)",Shante,Lauretta,A group of friends is considering whether or n...,"Now, suppose that Shante got vaccinated regard...",0,"Now, suppose that Shante did not get vaccinate...",0
1,0.0.0,0,0,0,"[6, 4, 6]","(Shante, Kalene)",Shante,Kalene,A group of friends is considering whether or n...,"Now, suppose that Shante got vaccinated regard...",1,"Now, suppose that Shante did not get vaccinate...",1
2,0.0.0,0,0,0,"[6, 4, 6]","(Shante, Aisha)",Shante,Aisha,A group of friends is considering whether or n...,"Now, suppose that Shante got vaccinated regard...",1,"Now, suppose that Shante did not get vaccinate...",1
3,0.0.0,0,0,0,"[6, 4, 6]","(Kalene, Aisha)",Kalene,Aisha,A group of friends is considering whether or n...,"Now, suppose that Kalene got vaccinated regard...",1,"Now, suppose that Kalene did not get vaccinate...",0
4,0.0.0,0,0,0,"[6, 4, 6]","(Kalene, Lauretta)",Kalene,Lauretta,A group of friends is considering whether or n...,"Now, suppose that Kalene got vaccinated regard...",0,"Now, suppose that Kalene did not get vaccinate...",0

In [8]:
df_cf.head(30)

,Task ID,Context ID,Sample ID,Replicate ID,Nodes per BCC,Cause-effect pair,Cause,Effect,Context,Question (cause = True),True (cause = True),Question (cause = False),True (cause = False)
0,0.0.0,0,0,0,"[6, 4, 6]","(Shante, Lauretta)",Shante,Lauretta,A group of friends is considering whether or n...,"Now, suppose that Shante got vaccinated regard...",0,"Now, suppose that Shante did not get vaccinate...",0
1,0.0.0,0,0,0,"[6, 4, 6]","(Shante, Kalene)",Shante,Kalene,A group of friends is considering whether or n...,"Now, suppose that Shante got vaccinated regard...",1,"Now, suppose that Shante did not get vaccinate...",1
2,0.0.0,0,0,0,"[6, 4, 6]","(Shante, Aisha)",Shante,Aisha,A group of friends is considering whether or n...,"Now, suppose that Shante got vaccinated regard...",1,"Now, suppose that Shante did not get vaccinate...",1
3,0.0.0,0,0,0,"[6, 4, 6]","(Kalene, Aisha)",Kalene,Aisha,A group of friends is considering whether or n...,"Now, suppose that Kalene got vaccinated regard...",1,"Now, suppose that Kalene did not get vaccinate...",0
4,0.0.0,0,0,0,"[6, 4, 6]","(Kalene, Lauretta)",Kalene,Lauretta,A group of friends is considering whether or n...,"Now, suppose that Kalene got vaccinated regard...",0,"Now, suppose that Kalene did not get vaccinate...",0
5,0.0.0,0,0,0,"[6, 4, 6]","(Aisha, Lauretta)",Aisha,Lauretta,A group of friends is considering whether or n...,"Now, suppose that Aisha got vaccinated regardl...",0,"Now, suppose that Aisha did not get vaccinated...",0
6,0.0.1,0,0,1,"[6, 4, 6]","(Shante, Lauretta)",Shante,Lauretta,A group of friends is considering whether or n...,"Now, suppose that Shante got vaccinated regard...",0,"Now, suppose that Shante did not get vaccinate...",0
7,0.0.1,0,0,1,"[6, 4, 6]","(Shante, Kalene)",Shante,Kalene,A group of friends is considering whether or n...,"Now, suppose that Shante got vaccinated regard...",1,"Now, suppose that Shante did not get vaccinate...",1
8,0.0.1,0,0,1,"[6, 4, 6]","(Shante, Aisha)",Shante,Aisha,A group of friends is considering whether or n...,"Now, suppose that Shante got vaccinated regard...",1,"Now, suppose that Shante did not get vaccinate...",1
9,0.0.1,0,0,1,"[6, 4, 6]","(Kalene, Aisha)",Kalene,Aisha,A group of friends is considering whether or n...,"Now, suppose that Kalene got vaccinated regard...",1,"Now, suppose that Kalene did not get vaccinate...",0
10,0.0.1,0,0,1,"[6, 4, 6]","(Kalene, Lauretta)",Kalene,Lauretta,A group of friends is considering whether or n...,"Now, suppose that Kalene got vaccinated regard...",0,"Now, suppose that Kalene did not get vaccinate...",0
11,0.0.1,0,0,1,"[6, 4, 6]","(Aisha, Lauretta)",Aisha,Lauretta,A group of friends is considering whether or n...,"Now, suppose that Aisha got vaccinated regardl...",0,"Now, suppose that Aisha did not get vaccinated...",0
12,0.0.2,0,0,2,"[6, 4, 6]","(Shante, Lauretta)",Shante,Lauretta,A group of friends is considering whether or n...,"Now, suppose that Shante got vaccinated regard...",0,"Now, suppose that Shante did not get vaccinate...",0
13,0.0.2,0,0,2,"[6, 4, 6]","(Shante, Kalene)",Shante,Kalene,A group of friends is considering whether or n...,"Now, suppose that Shante got vaccinated regard...",1,"Now, suppose that Shante did not get vaccinate...",1
14,0.0.2,0,0,2,"[6, 4, 6]","(Shante, Aisha)",Shante,Aisha,A group of friends is considering whether or n...,"Now, suppose that Shante got vaccinated regard...",1,"Now, suppose that Shante did not get vaccinate...",1
15,0.0.2,0,0,2,"[6, 4, 6]","(Kalene, Aisha)",Kalene,Aisha,A group of friends is considering whether or n...,"Now, suppose that Kalene got vaccinated regard...",1,"Now, suppose that Kalene did not get vaccinate...",0
16,0.0.2,0,0,2,"[6, 4, 6]","(Kalene, Lauretta)",Kalene,Lauretta,A group of friends is considering whether or n...,"Now, suppose that Kalene got vaccinated regard...",0,"Now, suppose that Kalene did not get vaccinate...",0
17,0.0.2,0,0,2,"[6, 4, 6]","(Aisha, Lauretta)",Aisha,Lauretta,A group of friends is considering whether or n...,"Now, suppose that Aisha got vaccinated regardl...",0,"Now, suppose that Aisha did not get vaccinated...",0
18,0.0.3,0,0,3,"[6, 4, 6]","(Shante, Lauretta)",Shante,Lauretta,A group of friends is considering whether or n...,"Now, suppose that Shante got vaccinated regard...",0,"Now, suppose that Shante did not get vaccinate...",0
19,0.0.3,0,0,3,"[6, 4, 6]","(Shante, Kalene)",Shante,Kalene,A group of friends is considering whether or n...,"Now, suppose that Shante got vaccinated regard...",1,"Now, suppose that Shante did not get vaccinate...",1
20,0.0.3,0,0,3,"[6, 4, 6]","(Shante, Aisha)",Shante,Aisha,A group of friends is considering whether or n...,"Now, suppose that Shante got vaccinated regard...",1,"Now, suppose that Shante did not get vaccinate...",1
21,0.0.3,0,0,3,"[6, 4, 6]","(Kalene, Aisha)",Kalene,Aisha,A group of friends is considering whether or n...,"Now, suppose that Kalene got vaccinated regard...",1,"Now, suppose that Kalene did not get vaccinate...",0
22,0.0.3,0,0,3,"[6, 4, 6]","(Kalene, Lauretta)",Kalene,Lauretta,A group of friends is considering whether or n...,"Now, suppose that Kalene got vaccinated regard...",0,"Now, suppose that Kalene did not get vaccinate...",0
23,0.0.3,0,0,3,"[6, 4, 6]","(Aisha, Lauretta)",Aisha,Lauretta,A group of friends is considering whether or n...,"Now, suppose that Aisha got vaccinated regardl...",0,"Now, suppose that Aisha did not get vaccinated...",0
24,0.0.4,0,0,4,"[6, 4, 6]","(Shante, Lauretta)",Shante,Lauretta,A group of friends is considering whether or n...,"Now, suppose that Shante got vaccinated regard...",0,"Now, suppose that Shante did not get vaccinate...",0
25,0.0.4,0,0,4,"[6, 4, 6]","(Shante, Kalene)",Shante,Kalene,A group of friends is considering whether or n...,"Now, suppose that Shante got vaccinated regard...",1,"Now, suppose that Shante did not get vaccinate...",1
26,0.0.4,0,0,4,"[6, 4, 6]","(Shante, Aisha)",Shante,Aisha,A group of friends is considering whether or n...,"Now, suppose that Shante got vaccinated regard...",1,"Now, suppose that Shante did not get vaccinate...",1
27,0.0.4,0,0,4,"[6, 4, 6]","(Kalene, Aisha)",Kalene,Aisha,A group of friends is considering whether or n...,"Now, suppose that Kalene got vaccinated regard...",1,"Now, suppose that Kalene did not get vaccinate...",0
28,0.0.4,0,0,4,"[6, 4, 6]","(Kalene, Lauretta)",Kalene,Lauretta,A group of friends is considering whether or n...,"Now, suppose that Kalene got vaccinated regard...",0,"Now, suppose that Kalene did not get vaccinate...",0
29,0.0.4,0,0,4,"[6, 4, 6]","(Aisha, Lauretta)",Aisha,Lauretta,A group of friends is considering whether or n...,"Now, suppose that Aisha got vaccinated regardl...",0,"Now, suppose that Aisha did not get vaccinated...",0

In [9]:
l = len(df_factual[(df_factual["Context ID"] == 0) & (df_factual["Effect"] == "surgery")])
print("\nTotal factual q's per quantity per task:", l)

Total factual q's per quantity per task: 0

In [10]:
l = len(df_cf[(df_cf["Context ID"] == 0) & (df_cf["Cause-effect pair"] == ("pain", "surgery"))])
print("\nTotal counterfactual q's per quantity per task:", l)

Total counterfactual q's per quantity per task: 0

## Step 3: Get ground truth PNS values.

Get dictionary mapping cause-effect pairs to their PNS value.

Keys are the Context ID. Values are dictionaries whose keys are the cause-effect pair and whose values are the finite sample PNS computed using ground truth response vectors.

In [11]:
pns_dict = dg.get_pns_dict(verbose = False)
display(pns_dict)

{np.int64(0): {"('Shante', 'Lauretta')": np.float64(0.0085),
  "('Shante', 'Kalene')": np.float64(0.132),
  "('Shante', 'Aisha')": np.float64(0.037),
  "('Kalene', 'Aisha')": np.float64(0.303),
  "('Kalene', 'Lauretta')": np.float64(0.0775),
  "('Aisha', 'Lauretta')": np.float64(0.23),
  "[('Shante', 'Kalene'), ('Kalene', 'Aisha'), ('Aisha', 'Lauretta')]": np.float64(0.009199080000000002),
  "[('Shante', 'Kalene'), ('Kalene', 'Lauretta')]": np.float64(0.010230000000000001),
  "[('Shante', 'Aisha'), ('Aisha', 'Lauretta')]": np.float64(0.00851)},
 np.int64(1): {"('Gussie', 'Sharyn')": np.float64(0.0025),
  "('Gussie', 'Marcelina')": np.float64(0.265),
  "('Gussie', 'Alayna')": np.float64(0.12),
  "('Marcelina', 'Alayna')": np.float64(0.464),
  "('Marcelina', 'Sharyn')": np.float64(0.0125),
  "('Alayna', 'Sharyn')": np.float64(0.029),
  "[('Gussie', 'Marcelina'), ('Marcelina', 'Alayna'), ('Alayna', 'Sharyn')]": np.float64(0.0035658400000000007),
  "[('Gussie', 'Marcelina'), ('Marcelina', 'Sharyn')]": np.float64(0.0033125000000000003),
  "[('Gussie', 'Alayna'), ('Alayna', 'Sharyn')]": np.float64(0.00348)},
 np.int64(2): {"('Antonette', 'Lynda')": np.float64(0.0165),
  "('Antonette', 'Bonny')": np.float64(0.4035),
  "('Antonette', 'Aliya')": np.float64(0.0355),
  "('Bonny', 'Aliya')": np.float64(0.085),
  "('Bonny', 'Lynda')": np.float64(0.0335),
  "('Aliya', 'Lynda')": np.float64(0.388),
  "[('Antonette', 'Bonny'), ('Bonny', 'Aliya'), ('Aliya', 'Lynda')]": np.float64(0.01330743),
  "[('Antonette', 'Bonny'), ('Bonny', 'Lynda')]": np.float64(0.013517250000000001),
  "[('Antonette', 'Aliya'), ('Aliya', 'Lynda')]": np.float64(0.013774)}}

## Step 4: Compute internal consistency thresholds.

Return a dictionary that maps compositions to their correctness threshold
for internal compositional consistency evaluation. Thresholds are the RAE
for each composition relative to the global quantity of interest, times a
multiplier of the user's choice. 

* RAE = (abs(global PNS - composition PNS) / global PNS)
* Threhold = RAE*multiplier
        
This method of obtaining the threshold accounts for the innate error owed
to PNS estimation on finite samples, while the multiplier represents the
user's tolerance level for errors larger than the finite sample error.

Keys are the Context ID. Values are dictionaries whose keys are the causal composition (denoted by a list of cause-effect pairs whose PNS values are multiplied) and whose values are the internal consistency threshold.

For public use, we export threholds with multiplier 1.0 so that the end user can select 
their own multiplier downstream.

In [12]:
# Not for export.
threshold_dict = dg.get_internal_consistency_thresholds(multiplier = 1.25)
display(threshold_dict)

{0: {"[('Shante', 'Kalene'), ('Kalene', 'Aisha'), ('Aisha', 'Lauretta')]": np.float64(0.10280588235294136),
  "[('Shante', 'Kalene'), ('Kalene', 'Lauretta')]": np.float64(0.2544117647058824),
  "[('Shante', 'Aisha'), ('Aisha', 'Lauretta')]": np.float64(0.0014705882352940576)},
 1: {"[('Gussie', 'Marcelina'), ('Marcelina', 'Alayna'), ('Alayna', 'Sharyn')]": np.float64(0.5329200000000003),
  "[('Gussie', 'Marcelina'), ('Marcelina', 'Sharyn')]": np.float64(0.40625000000000017),
  "[('Gussie', 'Alayna'), ('Alayna', 'Sharyn')]": np.float64(0.48999999999999994)},
 2: {"[('Antonette', 'Bonny'), ('Bonny', 'Aliya'), ('Aliya', 'Lynda')]": np.float64(0.24186136363636365),
  "[('Antonette', 'Bonny'), ('Bonny', 'Lynda')]": np.float64(0.22596590909090902),
  "[('Antonette', 'Aliya'), ('Aliya', 'Lynda')]": np.float64(0.20651515151515157)}}

In [13]:
# For export.
threshold_dict = dg.get_internal_consistency_thresholds(multiplier = 1.0)
display(threshold_dict)

{0: {"[('Shante', 'Kalene'), ('Kalene', 'Aisha'), ('Aisha', 'Lauretta')]": np.float64(0.08224470588235308),
  "[('Shante', 'Kalene'), ('Kalene', 'Lauretta')]": np.float64(0.20352941176470593),
  "[('Shante', 'Aisha'), ('Aisha', 'Lauretta')]": np.float64(0.001176470588235246)},
 1: {"[('Gussie', 'Marcelina'), ('Marcelina', 'Alayna'), ('Alayna', 'Sharyn')]": np.float64(0.4263360000000002),
  "[('Gussie', 'Marcelina'), ('Marcelina', 'Sharyn')]": np.float64(0.3250000000000001),
  "[('Gussie', 'Alayna'), ('Alayna', 'Sharyn')]": np.float64(0.39199999999999996)},
 2: {"[('Antonette', 'Bonny'), ('Bonny', 'Aliya'), ('Aliya', 'Lynda')]": np.float64(0.19348909090909092),
  "[('Antonette', 'Bonny'), ('Bonny', 'Lynda')]": np.float64(0.18077272727272722),
  "[('Antonette', 'Aliya'), ('Aliya', 'Lynda')]": np.float64(0.16521212121212125)}}